# Generated by Django 5.2 on 2025-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_perfilusuario_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
