# Generated by Django 5.2 on 2025-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_perfilusuario_limite_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rest_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
