# Generated by Django 5.2 on 2025-04-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_perfilusuario_rest_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='rest_token',
            new_name='reset_token',
        ),
    ]
