# Generated by Django 5.2 on 2025-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rest_token_perfilusuario_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
