# Generated by Django 5.2 on 2025-04-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_perfilusuario_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoria'),
        ),
    ]
